name: Scala CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Install sbt
        run: |
          echo "Installing sbt..."
          sudo apt update
          sudo apt install -y apt-transport-https curl
          echo "deb https://dl.cloudsmith.io/public/sbt/sbt-debian-debian10/ubuntu stable main" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          curl -fsSL https://dl.cloudsmith.io/public/sbt/sbt-debian-debian10/gpg.key | sudo tee /etc/apt/trusted.gpg.d/sbt.asc
          sudo apt update
          sudo apt install -y sbt
      - name: compile
        run: sbt compile
      - name: run tests
        run: sbt test

  run_tests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 22
       uses: actions/setup-java@v2
       with:
         java-version: '22'
         distribution: 'adopt'
     - name: Install sbt
       run: |
         echo "Installing sbt..."
         sudo apt update
         sudo apt install -y apt-transport-https curl
         echo "deb https://dl.cloudsmith.io/public/sbt/sbt-debian-debian10/ubuntu stable main" | sudo tee -a /etc/apt/sources.list.d/sbt.list
         curl -fsSL https://dl.cloudsmith.io/public/sbt/sbt-debian-debian10/gpg.key | sudo tee /etc/apt/trusted.gpg.d/sbt.asc
         sudo apt update
         sudo apt install -y sbt
     - name: Build Project and export Coverage
       env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       run: |
         export CI_BRANCH="${GITHUB_REF#refs/heads/}"
         sbt clean jacoco jacocoCoveralls
