name: Scala CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Install sbt
        run: |
          echo "Installing sbt..."
          curl -sL https://scala-ci.typesafe.com/download/1.5.5/sbt-1.5.5.tgz | tar xz
          sudo mv sbt /usr/local/bin
      - name: compile
        run: sbt compile
      - name: run tests
        run: sbt test

  run_tests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 22
       uses: actions/setup-java@v2
       with:
         java-version: '22'
         distribution: 'adopt'
     - name: Install sbt
       run: |
         echo "Installing sbt..."
         curl -sL https://scala-ci.typesafe.com/download/1.5.5/sbt-1.5.5.tgz | tar xz
         sudo mv sbt /usr/local/bin
     - name: Build Project and export Coverage
       env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       run: |
         export CI_BRANCH="${GITHUB_REF#refs/heads/}"
         sbt clean jacoco jacocoCoveralls
